<div class="page-login">
    <div class="card">
        <form class="card-body needs-validation main" method="POST" novalidate>
            <h5 class="card-title">Recovery Account</h5>

            <?php if($error): ?>
            <div class="alert alert-danger alert-dismissible fade show">
                <strong>Whoops!</strong> <?= $error ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <?php endif; ?>

            <?php if($success): ?>
                <div class="alert alert-primary">
                A message already sent to your inbox, please click the link inside of it to reset your password.
            </div>
            <?php else: ?>
                <p>We'll send the link to your account for reset password instructions.</p>
                <?= $form->field('email'); ?>
                <?= $form->csrfField('noob'); ?>

                <div>
                    <button class="btn btn-primary btn-block">Send</button>
                </div>
            <?php endif; ?>

            <div class="row pt-3">
                <div class="col-12 text-center">
                    <a href="<?= $this->router->to('adminMeLogin') ?>">Back to login</a>
                </div>
            </div>
        </form>
    </div>
</div>